#!/usr/bin/env bash
# codex-setup.sh — generate ~/.codex/config.toml with all your available backends.
#
# Detects which API keys you've set (env or shell rc), then writes a Codex
# config.toml pre-filled with provider blocks for every backend you can use.
# The first detected key becomes the default provider.
#
# Usage:
#   ./codex-setup.sh               # interactive: pick from detected keys
#   ./codex-setup.sh --dry-run     # print the config, don't write it
#   ./codex-setup.sh --force deepseek  # set deepseek as default

set -euo pipefail

DRY_RUN=0; FORCE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;; --force) FORCE="$2"; shift ;;
    *) echo "codex-setup.sh: unknown option: $1" >&2; exit 1 ;;
  esac; shift
done

get_key() {
  local var="$1"
  if [ -n "${!var:-}" ]; then printf '%s' "${!var}"; return 0; fi
  local f candidate
  for f in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.profile"; do
    [ -f "$f" ] || continue
    candidate="$(grep -E "^[[:space:]]*(export[[:space:]]+)?${var}=" "$f" 2>/dev/null|tail -1|sed -E "s/^[[:space:]]*(export[[:space:]]+)?${var}=//"|sed -E 's/^"(.*)"$/\1/; s/^'"'"'(.*)'"'"'$/\1/'||true)"
    if [ -n "${candidate:-}" ]; then printf '%s' "$candidate"; return 0; fi
  done; return 1
}

# Provider data: id label base_url key_var model need_noauth
# Separated by | for easy parsing.
PROVIDERS_DATA=(
  "deepseek|DeepSeek|https://api.deepseek.com/v1|DEEPSEEK_API_KEY|deepseek-chat|no"
  "dashscope|Qwen (Bailian)|https://dashscope.aliyuncs.com/compatible-mode/v1|DASHSCOPE_API_KEY|qwen-plus|no"
  "moonshot|Moonshot Kimi|https://api.moonshot.cn/v1|KIMI_API_KEY|kimi-k2.5|no"
  "zhipu|ZhipuAI GLM|https://open.bigmodel.cn/api/paas/v4|GLM_API_KEY|glm-4-flash|yes"
  "ark|Volcengine Ark|https://ark.cn-beijing.volces.com/api/v3|ARK_API_KEY|doubao-seed-2.0-code|yes"
  "longcat|Meituan LongCat|https://api.longcat.chat/openai|LONGCAT_API_KEY|LongCat-2.0|yes"
  "minimax|MiniMax|https://api.minimaxi.com/v1|MINIMAX_API_KEY|MiniMax-M3|yes"
  "tokenhub|Tencent TokenHub|https://api.lkeap.cloud.tencent.com/v1|HY_API_KEY|hy3-preview|yes"
  "siliconflow|SiliconFlow|https://api.siliconflow.cn/v1|SF_API_KEY|deepseek-ai/DeepSeek-V4-PRO|yes"
)

# Detect available providers.
available_ids=()
available_labels=()
for entry in "${PROVIDERS_DATA[@]}"; do
  IFS='|' read -r pid plabel purl pkey pmodel pnoauth <<< "$entry"
  k="$(get_key "$pkey" || true)"
  if [ -n "${k:-}" ]; then available_ids+=("$pid"); available_labels+=("$plabel"); fi
done

if [ ${#available_ids[@]} -eq 0 ]; then
  echo "codex-setup.sh: no known API keys found. Set one in your ~/.zshrc:" >&2
  echo "  export DEEPSEEK_API_KEY=sk-..." >&2
  echo "  export KIMI_API_KEY=sk-..." >&2
  exit 1
fi

# Pick default.
DEFAULT_ID="${available_ids[0]}"; DEFAULT_LABEL="${available_labels[0]}"
if [ -n "$FORCE" ]; then
  found=0; for i in "${!available_ids[@]}"; do
    if [ "${available_ids[$i]}" = "$FORCE" ]; then DEFAULT_ID="$FORCE"; DEFAULT_LABEL="${available_labels[$i]}"; found=1; break; fi
  done
  if [ "$found" = "0" ]; then echo "codex-setup.sh: provider '$FORCE' key not set." >&2; exit 1; fi
elif [ ${#available_ids[@]} -gt 1 ] && [ ! -t 0 ]; then
  # Non-interactive with multiple keys — use first.
  :
elif [ ${#available_ids[@]} -gt 1 ]; then
  echo "Multiple API keys detected. Which default provider?"
  for i in "${!available_ids[@]}"; do echo "  $((i+1))) ${available_labels[$i]}"; done
  read -r -p "Choice [1-${#available_ids[@]}] (default 1): " choice
  idx="${choice:-1}"
  if [ "$idx" -ge 1 ] 2>/dev/null && [ "$idx" -le "${#available_ids[@]}" ]; then
    DEFAULT_ID="${available_ids[$((idx-1))]}"; DEFAULT_LABEL="${available_labels[$((idx-1))]}"
  fi
fi

# Find default model.
DEFAULT_MODEL=""; for entry in "${PROVIDERS_DATA[@]}"; do
  IFS='|' read -r pid plabel purl pkey pmodel pnoauth <<< "$entry"
  [ "$pid" = "$DEFAULT_ID" ] && { DEFAULT_MODEL="$pmodel"; break; }
done

# ---- Generate config.toml --------------------------------------------------
CONFIG_PATH="$HOME/.codex/config.toml"

generate_toml() {
  echo "# Generated by codex-setup.sh — $(date +%Y-%m-%d)"
  echo "# Re-run codex-setup.sh to refresh when you add new API keys."
  echo ""
  echo "model = \"$DEFAULT_MODEL\""
  echo "model_provider = \"$DEFAULT_ID\""
  echo ""

  for entry in "${PROVIDERS_DATA[@]}"; do
    IFS='|' read -r pid plabel purl pkey pmodel pnoauth <<< "$entry"
    # Only include if available.
    found=0; for aid in "${available_ids[@]}"; do [ "$aid" = "$pid" ] && found=1; done
    [ "$found" = "0" ] && continue

    echo "# ---- $plabel ----"
    echo "[model_providers.$pid]"
    echo "name = \"$plabel\""
    echo "base_url = \"$purl\""
    echo "env_key = \"$pkey\""
    echo "wire_api = \"chat\""
    if [ "$pnoauth" = "yes" ]; then echo "requires_openai_auth = false"; fi
    echo ""
    echo "[profiles.$pid]"
    echo "model_provider = \"$pid\""
    echo "model = \"$pmodel\""
    echo ""
  done
}

if [ "$DRY_RUN" = "1" ]; then
  generate_toml
  echo "# Dry run — no file written."
else
  mkdir -p "$HOME/.codex"
  if [ -f "$CONFIG_PATH" ]; then
    cp "$CONFIG_PATH" "${CONFIG_PATH}.bak.$(date +%Y%m%d%H%M%S)"
    echo "Backed up existing config."
  fi
  generate_toml > "$CONFIG_PATH"
  echo "✓ Wrote $CONFIG_PATH (default: $DEFAULT_LABEL)"
  echo ""
  echo "Quick-switch profiles:"
  for id in "${available_ids[@]}"; do echo "  codex --profile $id"; done
fi
